name: Test Application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        cache: 'poetry'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Check code formatting with black
      run: poetry run black . --check

    - name: Check import sorting with isort
      run: poetry run isort -c . --profile black

    - name: Run tests
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: poetry run pytest
